dist: trusty
language: node_js
node_js:
  - 8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

jdk: oraclejdk8

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt=1.2.7


before_script:
  - git clone https://github.com/manuzhang/github-app
  - export PATH=/usr/bin:$PATH
script:
  - cd github-app && sbt "runMain io.github.manuzhang.graphql.GetAwesomeStreamingRepos --auth-token $GITHUB_TOKEN" && cp awesome-streaming-repos.json ../src/assets/repos.json && cd ..
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: manuzhang/awesome-streaming

env:
  - secure: nvqmUTAbzCRbGxJJLpWIvYiUcvN+amP4bAAAylvj/7fE3NwKktChMvFNXxmvdj1f0Ojp8L+UloCK5JHZe5iiHDKC8tR0APAmOa+vP4YqcZ9eG8K3j5ALqs9YlLtcmfKs7AzSh4A+aiSyjsCs4D5zEoRnCA1F1YdQUEGVUUIXGq7JhFJdpS0RNiRLyLO45nfSh4aVSvTjCbEM1UX53gsdIeDqZdDQS0/QKQRR9pXvDg1P6w2MDlkc1VE3AOZbe5nUDv8wVDoDbI1A33ym8waRyIrow9jAx/CA2equRHp5iGklHUSoLWSPzKoOZg/wLhkkOmnf1ztGn5DKG4GSFfp9N0ypiM92oPzUiJpxRsPcn8cwmHGr/IbJHRTZRH+XmiKwu8Z+LOmfAdguRco9JH9KTImDVQoywFAn6MZbaqz0aIimnnqcRaZf5/5sqHWnC7waJyKQSAfgYEVmIvUkpknxo+5Mv3lN5LscS1k1K69ipdjpNyjB2gbI0o1U0eYCzcyXB4a8CPFdp9vJmOI7aFGEhRvgaCFj9FjBocMGJdSenMdf+ERYQtJlW4e4rsog0Yp3dxKdDWIhkgL+pNfwzmyxUro7rrdUYd5VRcqZCPiMG26joEvQNPrQ98iVzC8u7tLhXVEDDu5TjltfXauPQfPF8Oxrl5QAxtfiixH7+LVgL00=
